reorder_imports = true
trailing_comma = "Never"
tab_spaces = 2
match_block_trailing_comma = false
condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
merge_imports = true
max_width = 110
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 25
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true